### ISSUE TITLE
Fitness for untrusted contents?

### ISSUE THREAD

**Issue by fabio-looker** [shellyln/liyad#1]
Hi! This looks like a really awesome library, and I'm hoping I can try it out. I was especially interested by the claim in the readme: 

> Secure execution for untrusted contents
> No host environment's symbols are accessible from evaluated user contents by default.
> Malicious codes can not make a serious attack

However, using the example from https://github.com/shellyln/liyad#build-your-new-dsl , and even after removing all presets other than `defaultConfig` and `installCore()` , I can still access a lot:

```js
const {	SExpression,
		defaultConfig,
		installCore,
	} = require('liyad')

let config = Object.assign({}, defaultConfig)
config = installCore(config)
let parse = SExpression(config)
let obj = {}

let fn1 = parse(`( -> (match) 
		(::match:constructor:prototype:foo= 1)
	)`)
fn1({})
console.log(obj.foo) //1

let fn2 = parse(`( -> (match) 
		(::match:constructor@assign ::match:constructor:prototype (# ("bar" 2)) )
	)`)
fn2({})
console.log(obj.bar) //2
```

Is there another way you would recommend using this to accept user-defined functions/predicates to apply to some data? Perhaps overriding the $get/$call functions to only access/call object properties that are "ownProperties" of the object in question?

**Comment by shellyln** [comment]
Hi! Thanks for posting the issue.
This is a vulnerability, and I've fix it on `fix-vulnerability-issue-1-a` branch:
https://github.com/shellyln/liyad/blob/fc40aadf695a1790b91d3c0b24a1edbb5fb7b471/src/s-exp/errors.ts#L30-L51

tests:
https://github.com/shellyln/liyad/blob/fc40aadf695a1790b91d3c0b24a1edbb5fb7b471/src/_spec/parser.spec.ts#L1224-L1225

Now, property access for `some_function_object['prototype']` in built-in operators throw an error.
(in some compiled code's context, all the property access for `obj['prototype']` throw an error)

**Comment by fabio-looker** [comment]
Oh, thank you so much for the quick attention! I am not sure of all possible similar issues, but I might point to the following reference:

> Dangerous methods and properties: arguments callee caller constructor eval prototype stack unwatch valueOf watch

http://adsafe.org

**Comment by shellyln** [comment]
> Dangerous methods and properties: arguments callee caller constructor eval prototype stack unwatch valueOf watch

Thank you for your advice!

Generally I think `Object.prototype.valueOf | toString` and any `Object.prototype.*` members (watch, unwatch ?) can use for prototype pollution attack from `obj.__proto__`, `func.prototype` (and `obj.constructor.prototype`), `Object.prototype`, `Object.setPrototypeOf()`.

Now accessing `__proto__` and `func.prototype` throw an error.
And I think `Object`, `arguments`, `arguments.callee`, `arguments.caller`, JavaScript's `eval` are not accessible by default.
Variable name resolution is separate with JavaScript runtime's resolution.

And in 6e540e487c740852b71e3cdb19c79435415343be , by always force `"use strict"`, `arguments.callee` and `Fuction.caller` function references are disabled.

**Comment by fabio-looker** [comment]
> arguments, arguments.callee, arguments.caller, JavaScript's eval are not accessible by default.

Yes, this makes sense based on the parser.

> `Object` is not accessible by default

I think Object is still available through {}.constructor, though I am not sure if it matters

Thank you!

**Comment by shellyln** [comment]
>> `Object` is not accessible by default
> I think Object is still available through {}.constructor, though I am not sure if it matters

Oops! I have to fix it!

> Perhaps overriding the $get/$call functions to only access/call object properties that are "ownProperties" of the object in question?

`$set` (or any assignment operators) should check property name is "ownProperties" or not exists.

Thank you!

**Comment by fabio-looker** [comment]
Accessing inherited properties still allows dangerous things to be found:
```js
	it('Can\'t Function.call(untrusted code)', () => {
		let rule = parse(`( -> (match) 
			((::match:toString:constructor@call null "return this" ) ())
		)`);
		console.log(rule({})) // returns the global object
	});
```

**Comment by shellyln** [comment]
fixed.
fce4cf20da270118052a2a3ce6231076919643f0

### prevent prototype pollution and globalThis leaking by following rules:

* Throws an error if  blacklist name properties are accessed (get/set)
  * `__proto__`, `__defineGetter__`, `__defineSetter__`, `__lookupGetter__`, `__lookupSetter__`
* Throws an error if  *some_func*[`'prototype'` | `'constructor'`] is accessed (get/set)
* Throws an error if  `Object[*]` (Object constructor's own properties) is accessed
* Throws an error if  `Function[*]` (Function constructor and descendants __proto__s' own properties) is accessed (get/set)
* Throws an error if  *some_func*`[*]` that is NOT *some_func* own property is accessed (get/set)

https://github.com/shellyln/liyad/blob/fce4cf20da270118052a2a3ce6231076919643f0/src/s-exp/errors.ts#L33-L86

**Comment by shellyln** [comment]
And i have enhanced config options to prevent ReDoS and DoS.

### prevent ReDoS and DoS by configuration flags:

* enableRegExpMatchOperators: enable / disable RegExp operators
* enableCompilationOperators: enable / disable compiling features; compiled fuctions ignore the maximum execution count limit
* maxEvalCount: limit the execution count

https://github.com/shellyln/liyad/blob/fce4cf20da270118052a2a3ce6231076919643f0/src/s-exp/types.ts#L96-L111

**Comment by shellyln** [comment]
Hi @fabio-looker 

> Accessing inherited properties still allows dangerous things to be found:

Fixed a vulnerability you found.
And i have enhanced the configuration object to prevent ReDoS/DoS attacks.

Thank you!

**Comment by fabio-looker** [comment]
Hi! Thank you so much. I think this should now be safe, and I am already using it in my project :)
